In [ ]:
import pandas as pd
#mount the google drive
from google.colab import files
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
#load the csv file
file = '/content/drive/MyDrive/ESIIL2025MSU/Project Data/LAKEPOWELL_all.txt'
df = pd.read_csv(file)
display(df.head())
print(df.dtypes)

          Date  Storage (af)
0  28-Jun-1963             0
1  29-Jun-1963          5400
2  30-Jun-1963          7400
3  01-Jul-1963          9400
4  02-Jul-1963         13400

Date            object
Storage (af)     int64
dtype: object

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%b-%Y')
display(df.head())
print(df.dtypes)

        Date  Storage (af)
0 1963-06-28             0
1 1963-06-29          5400
2 1963-06-30          7400
3 1963-07-01          9400
4 1963-07-02         13400

Date            datetime64[ns]
Storage (af)             int64
dtype: object

In [ ]:
#interactive plot over storage over time
import plotly.express as px

fig = px.line(df, x='Date', y=df['Storage (af)'], title='Lake Powell Storage: Monthly Mean')
fig.update_layout(
title_font_size=30, # Increase title font size
legend_title_font_size=20, # Increase legend title font size
xaxis=dict(title_font_size=20, tickfont=dict(size=18)), # Increase x-axis label font size
yaxis=dict(title='Storage (acre feet)', title_font_size=20, tickfont=dict(size=18)), # Increase y-axis label and tick font size legend=dict(font=dict(size=18)) # Increase legend font size
)
fig.show()
fig.write_html('Lake Powell Storage.html')